# -*- coding: utf-8 -*-
"""Firstpythonclass2-24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1XZeVzWLbl8GdwjHlHWL3pT49fYGTFn
"""

print('Hello world')

5**2

""" - #* multiplication
 - #** Power
- #+ plus
- #/ divide
"""



print(2-5)

print(10/4)

print (100*1.1**8)

x = 5
print(x)

x = 10

print(x)

items = 10
price = 2
returned = 3
sent = "My remaining items are"
net_items = items-returned
print(sent, net_items)

type(sent)

# Write three strings, set two of them as variables 'first_sent' and "second_sent"
# Write a comment above each variable describing it
# create a variable of age and print it between the sentence - "This person is 17 years old"

# This the name of the person
name = 'Jack'
# This is the age of the person
age = 30
# This is the job of the person
job = 'Engineer'

print(f"This person name {name} is and age is {age} and job is {job}")
print(f"This person name is {name}  and age is {age} and job is {job}")

print(f"Persons name is {name}")

age = 22
name = "Ammar"
print("This persons name is", name, "and his age is", age)

weight == 102
height == 10
BMI = weight/height
BMI

x = 4

x == 4

2 == 2

